-- La página "Productos" del admin gestionaba un catálogo de 4 productos de
-- ejemplo (migración 0005) que ya no tiene nada que ver con lo que se vende
-- de verdad: la tienda del sitio muestra el catálogo completo de MUK Hair
-- Perú (70 productos), pero vivía solo en un archivo estático generado por
-- scripts/sync-mukhair.mjs — nadie podía editar un precio desde el admin.
--
-- Esta migración: (1) agrega las columnas que le faltaban a `products` para
-- representar el catálogo real (línea de marca, categorías de filtro), (2)
-- retira los 4 productos de ejemplo, y (3) siembra los 70 productos reales
-- con los precios ya corregidos (ver web/scripts/sync-mukhair.mjs,
-- PRECIO_REAL). De acá en adelante, el sitio lee este catálogo — editar un
-- precio acá lo cambia en la tienda, con la web como respaldo si Supabase
-- no responde.

alter table products add column linea text;
alter table products add column tags text[] not null default '{}';

delete from products where name in ('Pomada clásica', 'Cera moldeadora', 'Shampoo anticaída', 'Aceite para barba');

insert into products (name, price, description, image_url, active, sort_order, linea, tags) values
  ('Savage MUK Barro para Peinado', 110, 'Fijación salvaje. Acabado semi mate con brillo. Fijación flexible. Resistente a la humedad. No se descascarilla. Soluble en agua. Fragancia de piel de mandarina.', 'https://ciezabarber.com/assets/productos/savage-muk-barro-para-peinado.webp', true, 0, 'Savage', '{"estilismo","hombre"}'),
  ('Dry MUK Crema de Peinado', 110, 'Acabado ultramate. Fijación firme. Resistente a la humedad. No sedescascarilla. Soluble en agua. Fragancia de kiwi.', 'https://ciezabarber.com/assets/productos/dry-muk-crema-de-peinado.webp', true, 10, 'Dry', '{"estilismo","hombre"}'),
  ('Rough MUK Crema Moldeadora', 110, 'Brillo y fijación naturales. Fijación flexible. Resistente a la humedad. No se descascarilla. Soluble en agua. Fragancia de melón.', 'https://ciezabarber.com/assets/productos/rough-muk-crema-moldeadora.webp', true, 20, 'Rough', '{"estilismo","hombre"}'),
  ('Slick MUK Gomina', 110, 'Acabado muy brillante. Fijación fuerte. Resistente a la humedad. No se descascarilla. Soluble en agua. Fragancia de coco y vainilla.', 'https://ciezabarber.com/assets/productos/slick-muk-gomina.webp', true, 30, 'Slick', '{"estilismo","hombre"}'),
  ('Raw MUK Barro de Peinado', 110, 'Acabado muy brillante. Fijación firme. Resistente a la humedad. No se descascarilla. Soluble en agua. Fragancia de mango.', 'https://ciezabarber.com/assets/productos/raw-muk-barro-de-peinado.webp', true, 40, 'Raw', '{"estilismo","hombre"}'),
  ('Filthy MUK Crema de Peinado', 110, '• Fijación firme. • Acabado áspero. • Resistente a la humedad. • No se descascarilla. • Soluble en agua. • Fragancia de manzana verde.', 'https://ciezabarber.com/assets/productos/filthy-muk-crema-de-peinado.webp', true, 50, 'Filthy', '{"estilismo","hombre"}'),
  ('Hard MUK Barro de Peinado', 110, '• Fijación brutal. • Acabado mate y con poco brillo. • Fijación flexible. • Resistente a la humedad. • No se descascarilla. • Soluble en agua. • Fragancia de naranja.', 'https://ciezabarber.com/assets/productos/hard-muk-barro-de-peinado.webp', true, 60, 'Hard', '{"estilismo","hombre"}'),
  ('Travel Pack Trio Tratamiento Ultrasuave Deep MUK', 180, 'Descubre el poder reparador del Deep Muk Trio , el combo perfecto para restaurar y nutrir el cabello dañado. Este set incluye: • Shampoo : Limpia profundamente mientras protege e hidrata. • Acondicionador : Desenreda y suaviza, dejando el cabello manejable y brillante. • Tratamiento : Repara y fortalece desde la raíz hasta las puntas. Ideal para revitalizar el cabello seco o tratado químicamente. 💆‍♀️✨ ¡Llévalo contigo a donde quieras gracias a su práctico tamaño de 100 ml', 'https://ciezabarber.com/assets/productos/travel-pack-trio-tratamiento-ultrasuave-deep-muk.webp', true, 70, 'Deep', '{"packs"}'),
  ('Dúo Reparador Aceite de Argan', 282, 'MUK SPA ACEITE DE ARGAN SHAMPOO REPARADOR Repara, hidrata y suaviza cabellos deshidratados, dañados y quebradizos. Una lujosa mezcla de puro aceite de argán marroquí, proteínas hidrolizadas vegetales e ingredientes hidratantes que no añaden peso. MUK SPA ACEITE DE ARGAN ACONDICIONADOR REPARADOR Repara, hidrata y suaviza cabellos deshidratados, dañados y quebradizos. Una lujosa mezcla de puro aceite de argán marroquí aporta un acondicionamiento intenso, brillo e hidratación intensivos al tiempo que reduce el encrespamiento y doma el pelo rebelde.', 'https://ciezabarber.com/assets/productos/duo-reparador-aceite-de-argan.jpg', true, 80, 'MUK SPA', '{"packs"}'),
  ('Dúo Voluminizador Fat MUK', 220, 'FAT MUK SHAMPOO VOLUMINIZADOR Fórmula ligera. Aporta volumen y brillo. Engruesa y fortalece el cabello. Aporta plenitud y textura. Expande las hebras del cabello para conseguir un volumen increíble en cabellos finos y lacios. Es suave: está indicado para todo tipo de cabellos, incluidos los secos y los dañados. Deliciosa fragancia a pino. FAT MUK ACONDICIONADOR VOLUMINIZADOR Fórmula ligera. Aporta volumen y brillo. Engruesa engruesay fortalece el cabello. Aporta plenitud y textura. Expande las hebras del cabello para conseguir un volumen increíble en cabellos finos y lacios. Es suave: está ind', 'https://ciezabarber.com/assets/productos/duo-voluminizador-fat-muk.jpg', true, 90, 'Fat', '{"packs","shampoos"}'),
  ('Dúo Shampoo y Tratamiento Milagroso 20 en 1 Head MUK', 230, 'El tratamiento sin enjuague definitivo para todo tipo de cabellos. 1. Suaviza y alisa 2. Aporta un brillo increíble 3. Previene el encrespamiento del pelo rebelde 4. Nutre el cabello seco y dañado 5. Ayuda a prevenir las puntas abiertas 6. Reduce la ruptura de cabellos 7. Protege de la pérdida prematura del color 8. No añade más peso 9. Desenreda 10. Protege frente a los aparatos térmicos 11. Ayuda a fortalecer el cabello 12. Aporta volumen 13. Protege del agua salina, del cloro y del daño ambiental 14. Reduce el tiempo necesario para secar con secador 15. Hidrata 16. Impide la penetración de ', 'https://ciezabarber.com/assets/productos/duo-shampoo-y-tratamiento-milagroso-20-en-1-head-muk.jpg', true, 100, 'Head', '{"packs"}'),
  ('Dúo Realzador de Rizos con Fijación Extra Kinky MUK', 220, 'KINKY MUK CREMA HIDRATANTE SIN ENJUAGUE PARA DEFINIR RIZOS Intensa hidratación y restablecimiento de la humedad. Impide que el cabello se encrespe. Define los rizos. No aporta grasa. Resistente a la humedad. Fragancia a frutas. KINKY MUK REALZADOR DE RIZOS CON FIJACIÓN EXTRA Fijación fuerte y brillo natural. Evita el encrespamiento y doma los rizos rebeldes. Define y realza los rizos. Hidrata el cabello al tiempo que le da forma. Resistente a la humedad. Fragancia a frutas.', 'https://ciezabarber.com/assets/productos/duo-realzador-de-rizos-con-fijacion-extra-kinky-muk.jpg', true, 110, 'Kinky', '{"packs"}'),
  ('Dúo Deep y Tratamiento Milagroso 20 en 1', 234, 'El tratamiento sin enjuague definitivo para todo tipo de cabellos. 1. Suaviza y alisa 2. Aporta un brillo increíble 3. Previene el encrespamiento del pelo rebelde 4. Nutre el cabello seco y dañado 5. Ayuda a prevenir las puntas abiertas 6. Reduce la ruptura de cabellos 7. Protege de la pérdida prematura del color 8. No añade más peso 9. Desenreda 10. Protege frente a los aparatos térmicos 11. Ayuda a fortalecer el cabello 12. Aporta volumen 13. Protege del agua salina, del cloro y del daño ambiental 14. Reduce el tiempo necesario para secar con secador 15. Hidrata 16. Impide la penetración de ', 'https://ciezabarber.com/assets/productos/duo-deep-y-tratamiento-milagroso-20-en-1.jpg', true, 120, 'Deep', '{"packs"}'),
  ('Dúo Reparador Intense MUK', 220, 'INTENSE MUK SHAMPOO REPARADOR Equilibrio perfecto de hidratación y proteínas. Aumenta la fuerza, elasticidad y brillo del cabello. El pelo deja de romperse. El pelo no se “endurece”, no hay peligro de que el aporte proteico sea excesivo. Fragancia de mango. INTENSE MUK ACONDICIONADOR REPARADOR Equilibrio perfecto de hidratación y proteínas. Aumenta la fuerza, elasticidad y brillo del cabello. El pelo deja de romperse. El pelo no se “endurece”, no hay peligro de que el aporte proteico sea excesivo. Fragancia de mango.', 'https://ciezabarber.com/assets/productos/duo-reparador-intense-muk.jpg', true, 130, 'Intense', '{"packs","shampoos"}'),
  ('Dúo para Conservar el Color Vivid MUK', 220, 'VIVID MUK SHAMPOO PARA CONSERVAR EL COLOR Protección contra la pérdida del color y nutrición para cabellos teñidos. Fórmula ligera que desenreda. Equilibrada fórmula proteica e hidratante. Contiene zinc para una máxima protección del color. Fragancia de coco y vainilla. VIVID MUK ACONDICIONADOR PARA CONSERVAR EL COLOR Protección contra la pérdida del color y nutrición para cabellos teñidos. Desenreda en el acto. Nutre y suaviza. Equilibrada fórmula proteica e hidratante. Rico en nutrientes esenciales. Aumenta el brillo y la elasticidad del cabello. Fragancia de coco y vainilla.', 'https://ciezabarber.com/assets/productos/duo-para-conservar-el-color-vivid-muk.jpg', true, 140, 'Vivid', '{"packs"}'),
  ('Dúo Tonificador Blonde MUK', 227, 'BLONDE MUK SHAMPOO TONIFICADOR Reduce los tonos rojizos y amarillos del pelo rubio. Limpia el cabello suavemente al tiempo que lo nutre, dejándolo suave, brillante y con un rico color. Es adecuado para utilizarlo en todo tipo de pelo, incluidos los cabellos rubios, grises y blancos. Fragancia de melón. BLONDE MUK TRATAMIENTO TONIFICADOR DE 1 MINUTO Reduce los tonos rojizos y amarillos del pelo rubio al tiempo que desenreda y nutre a fondo el cabello. Devuelve la elasticidad del cabello. Fortalece el interior del cabello. Es adecuado para utilizarlo a diario en todo tipo de pelo, incluidos los ', 'https://ciezabarber.com/assets/productos/duo-tonificador-blonde-muk.jpg', true, 150, 'Blonde', '{"packs"}'),
  ('Dúo Shampoo y Mascarilla Aceite de Argan', 297, 'MUK SPA ACEITE DE ARGAN SHAMPOO REPARADOR Repara, hidrata y suaviza cabellos deshidratados, dañados y quebradizos. Una lujosa mezcla de puro aceite de argán marroquí, proteínas hidrolizadas vegetales e ingredientes hidratantes que no añaden peso. MUK SPA ACEITE DE ARGAN MASCARILLA REPARADORA Reparación, hidrata y suaviza para cabellos deshidratados, dañados y quebradizos. Su lujosa mezcla de puro aceite de argán marroquí aporta un acondicionamiento, brillo e hidratación intensivos al tiempo que reduce el encrespamiento y doma el pelo rebelde.', 'https://ciezabarber.com/assets/productos/duo-shampoo-y-mascarilla-aceite-de-argan.webp', true, 160, 'MUK SPA', '{"packs"}'),
  ('Dúo Protector Térmico y Serum Suavizante Hot MUK', 220, 'HOT MUK PROTECTOR TÉRMICO Protege de los daños ocasionados por el calor. Acabado ligero y sin grasa. Impide la penetración de la humedad. Los protectores contra rayos ultravioleta impiden la pérdida de color y el daño causado por el sol. Fragancia de naranja cítrica. HOT MUK SERUM SUAVIZANTE Acabado ligero y sin grasa. Proporciona un brillo definitivo. Elimina la electricidad estática y doma el pelo rebelde. Los protectores contra rayos ultravioleta impiden la pérdida de color y el daño causado por el sol. Fragancia de naranja cítrica.', 'https://ciezabarber.com/assets/productos/duo-protector-termico-y-serum-suavizante-hot-muk.jpg', true, 170, 'Hot', '{"estilismo","packs"}'),
  ('Dúo Ultrasuave Deep MUK', 220, 'DEEP MUK SHAMPOO ULTRASUAVE Nutre al tiempo que limpia el cabello suavemente. Deja el cabello suave como la seda y brillante. Restablece los nutrientes y la hidratación perdidos. Es lo suficientemente suave como para utilizarlo a diario. Está indicado para todo tipo de cabellos. Fragancia de gardenia. DEEP MUK ACONDICIONADOR ULTRASUAVE Desenreda en el acto. Deja el cabello suave como la seda y brillante. Restablece los nutrientes y la hidratación perdidos. Está indicado para todo tipo de cabellos. Fragancia de gardenia.', 'https://ciezabarber.com/assets/productos/duo-ultrasuave-deep-muk.jpg', true, 180, 'Deep', '{"packs","shampoos"}'),
  ('Dúo Realzador de Rizos Kinky MUK', 220, 'KINKY MUK CREMA HIDRATANTE SIN ENJUAGUE PARA DEFINIR RIZOS Intensa hidratación y restablecimiento de la humedad. Impide que el cabello se encrespe. Define los rizos. No aporta grasa. Resistente a la humedad. Fragancia a frutas. KINKY MUK REALZADOR DE RIZOS Fijación y brillo naturales. Impide que el cabello se encrespe. Define y realza los rizos. Hidrata el cabello al tiempo que le da forma. Resistente a la humedad. Fragancia a frutas.', 'https://ciezabarber.com/assets/productos/duo-realzador-de-rizos-kinky-muk.jpg', true, 190, 'Kinky', '{"estilismo","packs"}'),
  ('Escoge Tu Linea', 180, '¡ SOLO QUEDAN 2 FILTHY DE 50 GRAMOS ! DRY DE 50 GRAMOS (AGOTADO) – También puedes armar tu duo entre cualquiera de nuestros 7 tipos de barros DÉJANOS TU COMBINACIÓN EN LOS COMENTARIOS (Que se encuentra en la sección «Método de Envío»)', 'https://ciezabarber.com/assets/productos/escoge-tu-linea.webp', true, 200, 'muk', '{"estilismo","hombre","packs"}'),
  ('Savage MUK Duo Gift Pack', 180, 'El duo perfecto. una lata de 95 gr. para el baño y una lata de 50 gr. para el bolso deportivo o de viaje.', 'https://ciezabarber.com/assets/productos/savage-muk-duo-gift-pack.webp', true, 210, 'Savage', '{"estilismo","hombre","packs"}'),
  ('Rough MUK Duo Gift Pack', 180, 'El duo perfecto. una lata de 95 gr. para el baño y una lata de 50 gr. para el bolso deportivo o de viaje.', 'https://ciezabarber.com/assets/productos/rough-muk-duo-gift-pack.webp', true, 220, 'Rough', '{"estilismo","hombre","packs"}'),
  ('Barros de 95 + 95 Gramos', 220, 'Puedes armar tu duo entre cualquiera de nuestros 7 tipos de barros DÉJANOS TU COMBINACIÓN EN LOS COMENTARIOS (Que se encuentra en la sección «Método de Envío»)', 'https://ciezabarber.com/assets/productos/barros-de-95-95-gramos.webp', true, 230, 'muk', '{"estilismo","hombre","packs"}'),
  ('Raw MUK Duo Gift Pack', 180, 'El duo perfecto. una lata de 95 gr. para el baño y una lata de 50 gr. para el bolso deportivo o de viaje.', 'https://ciezabarber.com/assets/productos/raw-muk-duo-gift-pack.webp', true, 240, 'Raw', '{"estilismo","hombre","packs"}'),
  ('Filthy MUK Duo Gift Pack', 180, 'El duo perfecto. una lata de 95 gr. para el baño y una lata de 50 gr. para el bolso deportivo o de viaje.', 'https://ciezabarber.com/assets/productos/filthy-muk-duo-gift-pack.webp', true, 250, 'Filthy', '{"estilismo","hombre","packs"}'),
  ('Hard MUK Duo Gift Pack', 180, 'El duo perfecto. una lata de 95 gr. para el baño y una lata de 50 gr. para el bolso deportivo o de viaje.', 'https://ciezabarber.com/assets/productos/hard-muk-duo-gift-pack.webp', true, 260, 'Hard', '{"estilismo","hombre","packs"}'),
  ('Dry MUK Duo Gift Pack', 180, 'El duo perfecto, una lata de 95 gr. para el baño y una lata de 50 gr. para el bolso deportivo o de viaje.', 'https://ciezabarber.com/assets/productos/dry-muk-duo-gift-pack.webp', true, 270, 'Dry', '{"estilismo","hombre","packs"}'),
  ('Duo Intense MUK 500ml', 352, '', 'https://ciezabarber.com/assets/productos/duo-intense-muk-500ml.png', true, 280, 'Intense', '{}'),
  ('Dúo Tratamiento Ultrasuave Deep MUK', 227, 'DEEP MUK ACONDICIONADOR ULTRASUAVE SIN ENJUAGUE Desenreda en el acto. Deja el cabello sedoso y brillante. Fortalece y protege. Restablece los nutrientes y la hidratación perdida. Fórmula ligera. Está indicado para todo tipo de cabellos. Fragancia de gardenia. DEEP MUK TRATAMIENTO ULTRASUAVE DE 1 MINUTO Suavidad y brillo intensos. Deja el cabello sedoso y brillante. Devuelve elasticidad al cabello. Fortalece el cabello desde el interior. Restablece los nutrientes y la hidratación perdida. Está indicado para todo tipo de cabellos. Utilízalo semanalmente, o cada vez que te laves con shampoo si tu', 'https://ciezabarber.com/assets/productos/duo-tratamiento-ultrasuave-deep-muk.jpg', true, 290, 'Deep', '{"packs"}'),
  ('Dúo Shampoo y Tratamiento Aceite de Argan', 312, 'MUK SPA ACEITE DE ARGAN SHAMPOO REPARADOR Repara, hidrata y suaviza cabellos deshidratados, dañados y quebradizos. Una lujosa mezcla de puro aceite de argán marroquí, proteínas hidrolizadas vegetales e ingredientes hidratantes que no añaden peso. MUK SPA ACEITE DE ARGÁN TRATAMIENTO Está indicado para todo tipo de cabellos. Una lujosa mezcla de fácil absorción de puro aceite de argán marroquí, aceite de linaza, aceite de almendras dulces y aloe vera. Aporta un acondicionamiento, brillo e hidratación intensivos al tiempo que disminuye el encrespamiento y doma el pelo rebelde.', 'https://ciezabarber.com/assets/productos/duo-shampoo-y-tratamiento-aceite-de-argan.jpg', true, 300, 'MUK SPA', '{"packs"}'),
  ('Trío Tratamiento Aceite de Argan', 453, '', 'https://ciezabarber.com/assets/productos/trio-tratamiento-aceite-de-argan.webp', true, 310, 'MUK SPA', '{"packs"}'),
  ('Dúo Tratamiento Reparador Intense MUK', 227, 'INTENSE MUK SHAMPOO REPARADOR Equilibrio perfecto de hidratación y proteínas. Aumenta la fuerza, elasticidad y brillo del cabello. El pelo deja de romperse. El pelo no se “endurece”, no hay peligro de que el aporte proteico sea excesivo. Fragancia de mango. INTENSE MUK TRATAMIENTO REPARADOR Equilibrio perfecto de hidratación y proteínas. Aumenta la fuerza, elasticidad y brillo del cabello. El pelo deja de romperse. El pelo no se “endurece”, no hay peligro de que el aporte proteico sea excesivo. Fragancia de mango.', 'https://ciezabarber.com/assets/productos/duo-tratamiento-reparador-intense-muk.jpg', true, 320, 'Intense', '{"packs"}'),
  ('Trío Tratamiento Ultrasuave Deep MUK', 337, 'TRÍO TRATAMIENTO ULTRASUAVE DEEP MUK DEEP MUK SHAMPOO ULTRASUAVE Nutre al tiempo que limpia el cabello suavemente. Deja el cabello suave como la seda y brillante. Restablece los nutrientes y la hidratación perdidos. Es lo suficientemente suave como para utilizarlo a diario. Está indicado para todo tipo de cabellos. DEEP MUK ACONDICIONADOR ULTRASUAVE SIN ENJUAGUE Desenreda en el acto. Deja el cabello sedoso y brillante. Fortalece y protege. Restablece los nutrientes y la hidratación perdida. Fórmula ligera. Está indicado para todo tipo de cabellos. DEEP MUK TRATAMIENTO ULTRASUAVE DE 1 MINUTO Su', 'https://ciezabarber.com/assets/productos/trio-tratamiento-ultrasuave-deep-muk.webp', true, 330, 'Deep', '{"packs"}'),
  ('mr. muk shampoo de estilizado y textura + Barro de 95 gr.', 220, '', 'https://ciezabarber.com/assets/productos/mr-muk-shampoo-de-estilizado-y-textura-barro-de-95-gr.webp', true, 340, 'mr. muk', '{"hombre","packs"}'),
  ('Dúo Barro 95g y Hard Shampoo', 220, 'Puedes escoger entre cualquiera de nuestros 7 tipos de barros DÉJANOS TU COMBINACIÓN EN LOS COMENTARIOS (Que se encuentra en la sección «Método de Envío»)', 'https://ciezabarber.com/assets/productos/duo-barro-95g-y-hard-shampoo.webp', true, 350, 'Hard', '{"packs"}'),
  ('Trío Tratamiento Reparador Intense MUK', 337, 'TRÍO TRATAMIENTO REPARADOR INTENSE MUK INTENSE MUK SHAMPOO REPARADOR Equilibrio perfecto de hidratación y proteínas. Aumenta la fuerza, elasticidad y brillo del cabello. El pelo deja de romperse. El pelo no se “endurece”, no hay peligro de que el aporte proteico sea excesivo. Fragancia de mango. INTENSE MUK ACONDICIONADOR REPARADOR Equilibrio perfecto de hidratación y proteínas. Aumenta la fuerza, elasticidad y brillo del cabello. INTENSE MUK TRATAMIENTO REPARADOR Equilibrio perfecto de hidratación y proteínas. Aumenta la fuerza, elasticidad y brillo del cabello. El pelo deja de romperse. El p', 'https://ciezabarber.com/assets/productos/trio-tratamiento-reparador-intense-muk.webp', true, 360, 'Intense', '{"packs"}'),
  ('Slick MUK Duo Gift Pack', 180, 'El duo perfecto, una lata de 95 gr. para el baño y una lata de 50 gr. para el bolso deportivo o de viaje.', 'https://ciezabarber.com/assets/productos/slick-muk-duo-gift-pack.webp', true, 370, 'Slick', '{"estilismo","packs"}'),
  ('Fat MUK Polvo Voluminizador', 90, 'Spray voluminizador para cabello fino: aporta cuerpo y textura sin apelmazar Si tienes el cabello fino, sin forma y que pierde volumen a los pocos minutos de peinarlo, este spray voluminizador para cabello fino será tu mejor aliado. Su fórmula ligera está diseñada para aportar cuerpo y textura sin apelmazar , dejando el pelo con un aspecto natural, suelto y con movimiento, como recién salido del salón. A diferencia de otros productos que dejan el cabello pesado o rígido, nuestro spray voluminizador envuelve cada hebra con una capa ligera que aumenta el grosor visual y mejora la textura desde l', 'https://ciezabarber.com/assets/productos/spray-volumen-fat-muk.png', true, 380, 'Fat', '{"estilismo"}'),
  ('mr. muk Shampoo de estilizado y textura', 110, 'Un shampoo de estilizado y peinado que crea volúmen en la ducha, dejando tu cabello fuerte y lujosamente texturizado. Para mas cuerpo no apliques acondicionador.', 'https://ciezabarber.com/assets/productos/mr-muk-shampoo-de-estilizado-y-textura.webp', true, 390, 'mr. muk', '{"hombre"}'),
  ('mr. muk Shampoo de cabello, barba y cuerpo', 115, 'Shampoo ideal para todo tipo de cabello y piel. Este shampoo multiuso, tres en uno, deja tu cabello y barba totalmente suave mientras nutre e hidrata tu cuerpo. No puede ser más simple.', 'https://ciezabarber.com/assets/productos/mr-muk-shampoo-de-cabello-barba-y-cuerpo.webp', true, 400, 'mr. muk', '{"hombre"}'),
  ('Head Shampoo para Cuero Cabelludo Grasoso', 110, 'Para cuellos cabelludos grasosos y puntas secas. Quita suavemente la grasa del cuero cabelludo y controla la producción de sebo. No remueve con dureza. Protege y nutre las puntas secas y sensibles. Suave fórmula apta para cabellos teñidos. Está indicado para todo tipo de cabellos. Fragancia de manzana verde.', 'https://ciezabarber.com/assets/productos/shampoo-para-cuero-cabelludo-grasoso.jpg', true, 410, 'Head', '{"hombre","shampoos"}'),
  ('Head MUK Tratamiento Milagroso 20 en 1', 117, 'El tratamiento sin enjuague definitivo para todo tipo de cabellos. 1. Suaviza y alisa 2. Aporta un brillo increíble 3. Previene el encrespamiento del pelo rebelde 4. Nutre el cabello seco y dañado 5. Ayuda a prevenir las puntas abiertas 6. Reduce la ruptura de cabellos 7. Protege de la pérdida prematura del color 8. No añade más peso 9. Desenreda 10. Protege frente a los aparatos térmicos 11. Ayuda a fortalecer el cabello 12. Aporta volumen 13. Protege del agua salina, del cloro y del daño ambiental 14. Reduce el tiempo necesario para secar con secador 15. Hidrata 16. Impide la penetración de ', 'https://ciezabarber.com/assets/productos/head-muk-tratamiento-milagroso-20-en-1.jpg', true, 420, 'Head', '{"estilismo","tratamientos"}'),
  ('Mr MUK Aceite para la Barba', 110, 'Para la suavidad y el control del vello facial grueso y indisciplinado. Penetra en la barba para suavizar y dar forma. Se puede utilizar como suavizante previo al afeitado de cara completa. Ideal para uso diario. Ligero, masculino, inspirado en el aroma de ‘L’Homme Prada’.', 'https://ciezabarber.com/assets/productos/mr-muk-aceite-para-la-barba.jpg', true, 430, 'mr. muk', '{"hombre"}'),
  ('Hot MUK Protector Térmico', 110, 'Protege de los daños ocasionados por el calor. Acabado ligero y sin grasa. Impide la penetración de la humedad. Los protectores contra rayos ultravioleta impiden la pérdida de color y el daño causado por el sol. Fragancia de naranja cítrica.', 'https://ciezabarber.com/assets/productos/hot-muk-protector-termico.jpg', true, 440, 'Hot', '{"estilismo"}'),
  ('Hot MUK Serum Suavizante', 110, 'Acabado ligero y sin grasa. Proporciona un brillo definitivo. Elimina la electricidad estática y doma el pelo rebelde. Los protectores contra rayos ultravioleta impiden la pérdida de color y el daño causado por el sol. Fragancia de naranja cítrica.', 'https://ciezabarber.com/assets/productos/hot-muk-serum-suavizante.jpg', true, 450, 'Hot', '{"estilismo"}'),
  ('Blonde MUK Tratamiento Tonificador de 1 Minuto', 117, 'Reduce los tonos rojizos y amarillos del pelo rubio al tiempo que desenreda y nutre a fondo el cabello. Devuelve la elasticidad del cabello. Fortalece el interior del cabello. Es adecuado para utilizarlo a diario en todo tipo de pelo, incluidos los cabellos rubios, grises y blancos. Fragancia de melón.', 'https://ciezabarber.com/assets/productos/blonde-muk-tratamiento-tonificador-de-1-minuto.jpg', true, 460, 'Blonde', '{"tratamientos"}'),
  ('Blonde MUK Shampoo Tonificador', 110, 'Reduce los tonos rojizos y amarillos del pelo rubio. Limpia el cabello suavemente al tiempo que lo nutre, dejándolo suave, brillante y con un rico color. Es adecuado para utilizarlo en todo tipo de pelo, incluidos los cabellos rubios, grises y blancos. Fragancia de melón.', 'https://ciezabarber.com/assets/productos/blonde-muk-shampoo-tonificador.jpg', true, 470, 'Blonde', '{"shampoos"}'),
  ('Vivid MUK Shampoo para Conservar el Color', 110, 'Protección contra la pérdida del color y nutrición para cabellos teñidos. Fórmula ligera que desenreda. Equilibrada fórmula proteica e hidratante. Contiene zinc para una máxima protección del color. Fragancia de coco y vainilla.', 'https://ciezabarber.com/assets/productos/vivid-muk-shampoo-para-conservar-el-color.jpg', true, 480, 'Vivid', '{"shampoos"}'),
  ('Vivid MUK Acondicionador para Conservar el Color', 110, 'Protección contra la pérdida del color y nutrición para cabellos teñidos. Desenreda en el acto. Nutre y suaviza. Equilibrada fórmula proteica e hidratante. Rico en nutrientes esenciales. Aumenta el brillo y la elasticidad del cabello. Fragancia de coco y vainilla.', 'https://ciezabarber.com/assets/productos/vivid-muk-acondicionador-para-conservar-el-color.jpg', true, 490, 'Vivid', '{"shampoos"}'),
  ('Intense MUK Tratamiento Reparador', 117, 'Equilibrio perfecto de hidratación y proteínas. Aumenta la fuerza, elasticidad y brillo del cabello. El pelo deja de romperse. El pelo no se “endurece”, no hay peligro de que el aporte proteico sea excesivo. Fragancia de mango.', 'https://ciezabarber.com/assets/productos/intense-muk-tratamiento-reparador.jpg', true, 500, 'Intense', '{"tratamientos"}'),
  ('Intense MUK Shampoo Reparador', 110, 'Equilibrio perfecto de hidratación y proteínas. Aumenta la fuerza, elasticidad y brillo del cabello. El pelo deja de romperse. El pelo no se “endurece”, no hay peligro de que el aporte proteico sea excesivo. Fragancia de mango.', 'https://ciezabarber.com/assets/productos/intense-muk-shampoo-reparador.jpg', true, 510, 'Intense', '{"shampoos"}'),
  ('Intense MUK Acondicionador Reparador', 110, 'Equilibrio perfecto de hidratación y proteínas. Aumenta la fuerza, elasticidad y brillo del cabello. El pelo deja de romperse. El pelo no se “endurece”, no hay peligro de que el aporte proteico sea excesivo. Fragancia de mango.', 'https://ciezabarber.com/assets/productos/intense-muk-acondicionador-reparador.jpg', true, 520, 'Intense', '{"shampoos"}'),
  ('Fat MUK Shampoo Voluminizador', 110, 'Fórmula ligera. Aporta volumen y brillo. Engruesa y fortalece el cabello. Aporta plenitud y textura. Expande las hebras del cabello para conseguir un volumen increíble en cabellos finos y lacios. Es suave: está indicado para todo tipo de cabellos, incluidos los secos y los dañados. Deliciosa fragancia a pino.', 'https://ciezabarber.com/assets/productos/fat-muk-shampoo-voluminizador.jpg', true, 530, 'Fat', '{"shampoos"}'),
  ('Fat MUK Acondicionador Voluminizador', 110, 'Fórmula ligera. Aporta volumen y brillo. Engruesa engruesay fortalece el cabello. Aporta plenitud y textura. Expande las hebras del cabello para conseguir un volumen increíble en cabellos finos y lacios. Es suave: está indicado para todo tipo de cabellos, incluidos los secos y los dañados. Deliciosa fragancia a pino.', 'https://ciezabarber.com/assets/productos/fat-muk-acondicionador-voluminizador.jpg', true, 540, 'Fat', '{"shampoos"}'),
  ('Deep MUK Acondicionador Ultrasuave sin Enjuague', 110, 'Desenreda en el acto. Deja el cabello sedoso y brillante. Fortalece y protege. Restablece los nutrientes y la hidratación perdida. Fórmula ligera. Está indicado para todo tipo de cabellos. Fragancia de gardenia.', 'https://ciezabarber.com/assets/productos/deep-muk-acondicionador-ultrasuave-sin-enjuague.jpg', true, 550, 'Deep', '{"estilismo","shampoos"}'),
  ('Deep MUK Tratamiento Ultrasuave de 1 Minuto', 117, 'Suavidad y brillo intensos. Deja el cabello sedoso y brillante. Devuelve elasticidad al cabello. Fortalece el cabello desde el interior. Restablece los nutrientes y la hidratación perdida. Está indicado para todo tipo de cabellos. Utilízalo semanalmente, o cada vez que te laves con shampoo si tu cabello está extremadamente dañado. Fragancia de gardenia.', 'https://ciezabarber.com/assets/productos/deep-muk-tratamiento-ultrasuave-de-1-minuto.jpg', true, 560, 'Deep', '{"tratamientos"}'),
  ('Deep MUK Acondicionador Ultrasuave', 110, 'Desenreda en el acto. Deja el cabello suave como la seda y brillante. Restablece los nutrientes y la hidratación perdidos. Está indicado para todo tipo de cabellos. Fragancia de gardenia.', 'https://ciezabarber.com/assets/productos/deep-muk-acondicionador-ultrasuave.jpg', true, 570, 'Deep', '{"shampoos"}'),
  ('Deep MUK Shampoo Ultrasuave', 110, 'Nutre al tiempo que limpia el cabello suavemente. Deja el cabello suave como la seda y brillante. Restablece los nutrientes y la hidratación perdidos. Es lo suficientemente suave como para utilizarlo a diario. Está indicado para todo tipo de cabellos. Fragancia de gardenia.', 'https://ciezabarber.com/assets/productos/deep-muk-shampoo-ultrasuave.jpg', true, 580, 'Deep', '{"shampoos"}'),
  ('Hard MUK Shampoo de Peinado y Textura', 110, 'Aporta textura al natural y volumen a cabellos finos, lacios o difíciles de peinar. Su fórmula sin suavizante es ideal para el pelo corto o cortado en capas. Es ideal para usar a diario. Es apto para usar en cabellos teñidos. Fragancia de naranja.', 'https://ciezabarber.com/assets/productos/hard-muk-shampoo-de-peinado-y-textura.jpg', true, 590, 'Hard', '{"hombre","shampoos"}'),
  ('MUK SPA Aceite de Argan Mascarilla Reparadora', 156, 'Reparación, hidrata y suaviza para cabellos deshidratados, dañados y quebradizos. Su lujosa mezcla de puro aceite de argán marroquí aporta un acondicionamiento, brillo e hidratación intensivos al tiempo que reduce el encrespamiento y doma el pelo rebelde.', 'https://ciezabarber.com/assets/productos/muk-spa-aceite-de-argan-mascarilla-reparadora.webp', true, 600, 'MUK SPA', '{"tratamientos"}'),
  ('MUK SPA Aceite de Argán Tratamiento', 171, 'Está indicado para todo tipo de cabellos. Una lujosa mezcla de fácil absorción de puro aceite de argán marroquí, aceite de linaza, aceite de almendras dulces y aloe vera. Aporta un acondicionamiento, brillo e hidratación intensivos al tiempo que disminuye el encrespamiento y doma el pelo rebelde.', 'https://ciezabarber.com/assets/productos/muk-spa-aceite-de-argan-tratamiento.webp', true, 610, 'MUK SPA', '{"tratamientos"}'),
  ('MUK SPA Aceite de Argan Spray', 171, 'Está indicado para todo tipo de cabellos. Una lujosa y ligera mezcla de puro aceite de argán marroquí, aceite de linaza, aceite de almendras dulces y aloe vera. Aporta un acondicionamiento, brillo e hidratación intensivos al tiempo que disminuye el encrespamiento y doma el pelo rebelde.', 'https://ciezabarber.com/assets/productos/muk-spa-aceite-de-argan-spray.webp', true, 620, 'MUK SPA', '{"tratamientos"}'),
  ('MUK SPA Aceite de Argan Acondicionador Reparador', 141, 'Repara, hidrata y suaviza cabellos deshidratados, dañados y quebradizos. Una lujosa mezcla de puro aceite de argán marroquí aporta un acondicionamiento intenso, brillo e hidratación intensivos al tiempo que reduce el encrespamiento y doma el pelo rebelde.', 'https://ciezabarber.com/assets/productos/muk-spa-aceite-de-argan-acondicionador-reparador.webp', true, 630, 'MUK SPA', '{"shampoos"}'),
  ('MUK SPA Aceite de Argan Shampoo Reparador', 141, 'Repara, hidrata y suaviza cabellos deshidratados, dañados y quebradizos. Una lujosa mezcla de puro aceite de argán marroquí, proteínas hidrolizadas vegetales e ingredientes hidratantes que no añaden peso. Aporta un acondicionamiento, brillo e hidratación intensivos al tiempo que disminuye el encrespamiento y doma el pelo rebelde.', 'https://ciezabarber.com/assets/productos/muk-spa-aceite-de-argan-shampoo-reparador.webp', true, 640, 'MUK SPA', '{"shampoos"}'),
  ('Kinky MUK Realzador de Rizos con Fijación Extra', 110, 'Fijación fuerte y brillo natural. Evita el encrespamiento y doma los rizos rebeldes. Define y realza los rizos. Hidrata el cabello al tiempo que le da forma. Resistente a la humedad. Fragancia a frutas.', 'https://ciezabarber.com/assets/productos/kinky-muk-realzador-de-rizos-con-fijacion-extra.webp', true, 650, 'Kinky', '{"estilismo"}'),
  ('Kinky MUK Crema Hidratante sin Enjuague para Definir Rizos', 110, 'Intensa hidratación y restablecimiento de la humedad. Impide que el cabello se encrespe. Define los rizos. No aporta grasa. Resistente a la humedad. Fragancia a frutas.', 'https://ciezabarber.com/assets/productos/kinky-muk-crema-hidratante-sin-enjuague-para-definir-rizos.webp', true, 660, 'Kinky', '{"estilismo"}'),
  ('Kinky MUK Realzador de Rizos', 110, 'Fijación y brillo naturales. Impide que el cabello se encrespe. Define y realza los rizos. Hidrata el cabello al tiempo que le da forma. Resistente a la humedad. Fragancia a frutas.', 'https://ciezabarber.com/assets/productos/kinky-muk-realzador-de-rizos.webp', true, 670, 'Kinky', '{"estilismo"}'),
  ('Fat MUK Voluminizador', 110, 'Fórmula ligera. Aporta volumen y brillo. Engruesa y fortalece el cabello. Su boquilla regulable te ofrece la opción de utilizarlo como voluminizador general o para elevar la raíz. Expande las hebras del cabello para conseguir un volumen increíble en cabellos finos y lacios. Resistente a la humedad. Fragancia de bruma alpina.', 'https://ciezabarber.com/assets/productos/fat-muk-voluminizador.webp', true, 680, 'Fat', '{"estilismo"}'),
  ('Beach MUK Spray de Sal de Mar', 110, 'Sexy cabello de playa en una botella. Textura ligera. Las sales naturales del mar le dan al cabello una apariencia alborotada y sensual con una textura increíble. Utilizar en cabello seco o húmedo. Ligero acabado mate. Fragancia de melón.', 'https://ciezabarber.com/assets/productos/beach-muk-spray-de-sal-de-mar.webp', true, 690, 'Beach', '{"estilismo"}');
